import 'dart:io';

import 'package:ffmpeg_kit_flutter_new_video/ffmpeg_kit.dart';
import 'package:ffmpeg_kit_flutter_new_video/return_code.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;

/// Answers the two format questions v1 left open, **with measurements rather
/// than plausible reasoning**.
///
/// 1. **Can we decode HEIC/HEIF/AVIF at all?** They are rejected up front today,
///    which is a workaround and not a fix — HEIC is a common phone camera
///    format, so a user picks a photo they can see in their gallery and is told
///    it is unsupported. The planned fix is to transcode through the ffmpeg we
///    already ship, but whether *this* ffmpeg build can read the HEIF container
///    has never been checked. If it cannot, the fallback has to be Android's own
///    `BitmapFactory` instead (API 28+), which is a different design.
///
/// 2. **Do the claimed video formats actually work?** mkv/avi/3gp/m4v are
///    believed-good from the build's demuxer list but have never been observed
///    end to end.
///
/// The fixtures are real files generated by libheif (`tool/make_heic_fixture.py`)
/// and bundled as assets. **Known limit:** an iPhone's HEIC uses particular HEVC
/// profiles and often carries several items (tiles, thumbnails, depth maps), so
/// decoding this proves the container and codec path, not every camera file.
void formatSupportTests() {
  late Directory work;

  setUp(() async => work = await Directory.systemTemp.createTemp('formats'));
  tearDown(() async {
    if (work.existsSync()) await work.delete(recursive: true);
  });

  Future<File> fixture(String name) async {
    final data = await rootBundle.load('assets/format_fixtures/$name');
    final file = File(p.join(work.path, name));
    await file.writeAsBytes(data.buffer.asUint8List());
    return file;
  }

  testWidgets('REPORT: what this ffmpeg build can demux and decode', (
    tester,
  ) async {
    // Capability listing first: it needs no fixture, and if the HEIF demuxer is
    // simply absent the answer is settled without transcoding anything.
    for (final probe in ['-demuxers', '-decoders']) {
      final session = await FFmpegKit.execute('-hide_banner $probe');
      final out = await session.getAllLogsAsString() ?? '';
      final hits = out
          .split('\n')
          .where(
            (l) => RegExp(
              r'heif|heic|avif|hevc|h265|av1|matroska|3gp|mov',
              caseSensitive: false,
            ).hasMatch(l),
          )
          .map((l) => l.trim())
          .toList();
      debugPrint('>>> FORMATS $probe:\n${hits.join("\n")}');
    }
  });

  group('still images we currently reject', () {
    /// Transcodes to PNG and reports whether the result is genuinely decodable.
    ///
    /// Checks the pixels, not just ffmpeg's exit code: a zero exit with an empty
    /// or unreadable file would otherwise read as success.
    Future<bool> transcodes(String name) async {
      final source = await fixture(name);
      final out = File(p.join(work.path, '$name.png'));

      final session = await FFmpegKit.execute(
        '-y -i ${source.path} -frames:v 1 ${out.path}',
      );
      final ok = ReturnCode.isSuccess(await session.getReturnCode());
      if (!ok) {
        debugPrint(
          '>>> FORMATS $name: ffmpeg FAILED\n'
          '${await session.getAllLogsAsString()}',
        );
        return false;
      }
      if (!out.existsSync() || out.lengthSync() == 0) {
        debugPrint('>>> FORMATS $name: exit 0 but no output written');
        return false;
      }

      final decoded = img.decodeImage(await out.readAsBytes());
      debugPrint(
        '>>> FORMATS $name: OK → ${out.lengthSync()} bytes, '
        '${decoded?.width}x${decoded?.height}',
      );
      return decoded != null;
    }

    testWidgets('CONTROL: jpeg transcodes (proves the harness works)', (
      tester,
    ) async {
      // If this fails, nothing below means anything — the fixture or the ffmpeg
      // invocation is wrong rather than the format being unsupported.
      expect(await transcodes('fixture.jpg'), isTrue);
    });

    testWidgets('MEASURE: can ffmpeg read HEIC?', (tester) async {
      final ok = await transcodes('fixture.heic');
      debugPrint('>>> FINDING: ffmpeg HEIC decode = $ok');
      // Deliberately not asserted. This run exists to *answer* the question; a
      // false here selects the BitmapFactory design instead of failing the build.
    });

    testWidgets('MEASURE: can ffmpeg read AVIF?', (tester) async {
      final ok = await transcodes('fixture.avif');
      debugPrint('>>> FINDING: ffmpeg AVIF decode = $ok');
    });
  });

  testWidgets('MEASURE: the claimed video formats really are supported', (
    tester,
  ) async {
    // mkv/avi/3gp/m4v are listed as supported on the strength of ffmpeg's
    // demuxer list alone. This actually round-trips one frame through each.
    final source = File(p.join(work.path, 'src.mp4'));
    await FFmpegKit.execute(
      '-y -f lavfi -i testsrc2=size=320x240:rate=10:duration=1 '
      '-pix_fmt yuv420p ${source.path}',
    );

    final results = <String, bool>{};
    for (final ext in ['mkv', 'avi', '3gp', 'm4v', 'mov', 'webm']) {
      final container = File(p.join(work.path, 'clip.$ext'));
      final made = await FFmpegKit.execute(
        '-y -i ${source.path} ${container.path}',
      );
      if (!ReturnCode.isSuccess(await made.getReturnCode())) {
        results[ext] = false;
        continue;
      }

      // Read it back — writing a container proves the muxer, not the demuxer,
      // and it is the demuxer we depend on for a user's file.
      final frame = File(p.join(work.path, 'frame_$ext.png'));
      final read = await FFmpegKit.execute(
        '-y -i ${container.path} -frames:v 1 ${frame.path}',
      );
      results[ext] =
          ReturnCode.isSuccess(await read.getReturnCode()) &&
          frame.existsSync() &&
          frame.lengthSync() > 0;
    }

    debugPrint('>>> FINDING: video container round-trip = $results');
    expect(
      results['mp4'] ?? true,
      isTrue,
      reason: 'mp4 is the format every source produces',
    );
  });
}
